export const parts = [
    'hair',
    'ears',
    'eyes',
    'mouth',
    'neck',
    'leg',
    'accesories',
    'background',
];

export const options = {
    hair: ['default', 'bang', 'curls', 'elegant', 'quiff', 'short'],
    ears: ['default', 'tilt-backward', 'tilt-forward'],
    eyes: ['default', 'angry', 'naughty', 'panda', 'smart', 'star'],
    mouth: ['default', 'astonished', 'eating', 'laugh', 'tongue'],
    neck: ['default', 'bend-backward', 'bend-forward', 'thick'],
    leg: [
        'default',
        'bubble-tea',
        'cookie',
        'game-console',
        'tilt-backward',
        'tilt-forward',
    ],
    accesories: ['none', 'earings', 'flower', 'glasses', 'headphone'],
    background: [
        'blue50',
        'blue60',
        'blue70',
        'darkblue30',
        'darkblue50',
        'darkblue70',
        'green50',
        'green60',
        'green70',
        'grey40',
        'grey70',
        'grey80',
        'red50',
        'red60',
        'red70',
        'yellow50',
        'yellow60',
        'yellow70',
    ],
};

export const initialState = {
    hair: 'default',
    ears: 'default',
    eyes: 'default',
    mouth: 'default',
    neck: 'default',
    leg: 'default',
    accesories: 'none',
    background: 'blue50',
};
